config/routes.rb
Rails.application.routes.draw do
  get 'states' => 'country#all_states'

  get 'top_pop' => 'country#top_five_pop'

  get 'top_area' => 'country#top_five_area'

  root 'inventory#all_products'

  get 'product' => 'inventory#one_product'

  get 'category' => 'inventory#by_category'

  get 'new' => 'inventory#new'
  post 'new' => 'inventory#new'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  def all_states
  	@states = State.all
  end

  def top_five_pop
  	@states = State.order(population: :desc).limit(5)
  end

  def top_five_area
  	@states = State.order(area: :desc).limit(5)
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@products = Product.order(name: :desc)
  end

  def one_product
  	@product = Product.find(params[:id])
  end

  def by_category
  	@category = params[:category]
  	@products = Product.where(category: @category)
  end

  def new
  	if params[:name] != nil
  		product = Product.create(name: params[:name], price: params[:price], category: params[:category])
  		redirect_to product_path(id: product.id)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/country/_stateloop.html.erb
<div class="row">
	<% @states.each do |state| %>
		<div class="col-md-3">
			<div class="well">
				<h2><%= state.name %></h2>
				<p>Capitol: <strong><%= state.capitol %></strong></p>
				<p>Pop: <%= number_with_delimiter state.population %></p>
				<p>Area: <%= number_with_delimiter state.area %> sq. mi.</p>
			</div>
		</div>
	<% end %>
</div>

app/views/country/all_states.html.erb
<h1>All the States!</h1>

<%= render 'stateloop' %>

app/views/country/top_five_area.html.erb
<h1>Top Five: Largest States by Area</h1>

<%= render 'stateloop' %>

app/views/country/top_five_pop.html.erb
<h1>Top Five: Most Populous States</h1>

<%= render 'stateloop' %>

app/views/inventory/_productloop.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-3">
			<div class="well">
				<h3><%= link_to product.name, product_path(id: product.id) %></h3>
				<p><%= number_to_currency product.price %></p>
				<p><%= link_to product.category, category_path(category: product.category) %></p>
				<p><%= link_to "Show", product_path(id: product.id), class: "btn btn-info" %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/inventory/all_products.html.erb
<h1>Our Entire Selection!</h1>

<%= render 'productloop' %>

app/views/inventory/by_category.html.erb
<h1>All of Our <%= @category %> Products</h1>

<%= render 'productloop' %>

app/views/inventory/new.html.erb
<h1>Enter a New Product</h1>

<%= form_tag new_path do %>
	<%= text_field_tag :name, nil, placeholder: "Product Name", class: "form-control" %>
	<%= number_field_tag :price, nil, placeholder: "Price", class: "form-control" %>
	<%= text_field_tag :category, nil, placeholder: "Category Name", class: "form-control" %>
	<%= submit_tag "Create Product", class: "btn btn-success" %>
<% end %>

app/views/inventory/one_product.html.erb
<h1><%= @product.name %></h1>
<p><%= number_to_currency @product.price %></p>
<p>Found in our <%= @product.category %> section</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tech Talent Furniture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Furniture Home", root_path, class: "navbar-brand" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	      	<% if controller.controller_name == 'inventory' %>
	      		<li><%= link_to "Create New Product", new_path %></li>
	      	<% end %>
		      <li><%= link_to "States", states_path %></li>
	      	<% if controller.controller_name == 'country' %>
		      	<li><%= link_to "Top in Pop", top_pop_path %></li>
		      	<li><%= link_to "Top in Area", top_area_path %></li>
		      <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->	
	</nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>